# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omok_backend_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='omok_backend_rest.Room'),
        ),
    ]
